-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : fonsecarm
-- Date        : Friday, December 23 2016 13:00:41
-- Project     : Benchmark_Truth_16122016.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          2092          205         2092            0         0           0 0 0 0 /

RPTRST                                 -- Generated : Petrel
  BASIC=3 FLOWS /

RPTSOL                                 -- Generated : Petrel
  RESTART=2 FIP /

